server:
  port: 8085

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: derivdima@gmail.com
    password: kldk tzcj gdac bvmp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
